---
title: Verdwaald in de ruimte
hero_image: images/lost-in-space.png
description: Leer hoe je jouw eigen animatie kunt programmeren!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 26-09-2018
steps:
  - 
    title: Inleiding
  - 
    title: Een ruimteschip maken
  - 
    title: 'Uitdaging: je animatie verbeteren'
    challenge: true
  - 
    title: Animatie die zich steeds herhaalt
    completion:
      - engaged
  - 
    title: Zwevende aap
  - 
    title: Stuiterende asteroïde
  - 
    title: Flonkerende ster
    completion:
      - internal
  - 
    title: 'Uitdaging: maak je eigen animatie'
    challenge: true
  - 
    title: Wat nu?
