---
title: अंतराळात हरवले
hero_image: images/lost-in-space.png
description: आपले स्वतःचे अ‍ॅनिमेशन कसे तयार करायचे ते जाणून घ्या!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: परिचय
  - 
    title: एक अंतराळ यान अ‍ॅनिमेट करणे
  - 
    title: 'आव्हान : आपल्या अ‍ॅनिमेशनमध्ये सुधारणा करा'
    challenge: true
  - 
    title: आवर्ती (loops) वापरून अ‍ॅनिमेशन
    completion:
      - engaged
  - 
    title: तरंगणारे माकड
  - 
    title: उसळणारा लघुग्रह
  - 
    title: चमकणारा तारा
    completion:
      - internal
  - 
    title: 'आव्हान : आपले स्वतःचे अ‍ॅनिमेशन बनवा'
    challenge: true
  - 
    title: पुढे काय?
