---
title: Izgubljeni u svemiru
hero_image: images/lost-in-space.png
description: U ovom projektu naučit ćeš programirati svoje animacije!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Uvod
  - 
    title: Animacija svemirskog broda
  - 
    title: 'Izazov: poboljšaj svoju animaciju'
    challenge: true
  - 
    title: Animacija pomoću petlje
    completion:
      - engaged
  - 
    title: Majmun koji lebdi
  - 
    title: Asteroid koji odskakuje
  - 
    title: Sjajna zvijezda
    completion:
      - internal
  - 
    title: 'Izazov: napravi vlastitu animaciju'
    challenge: true
  - 
    title: Što dalje?
