---
title: Ar goll yn y gofod
hero_image: images/lost-in-space.png
description: Dysga sut i raglenni dy animeiddiad dy hunan!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
- title: Cyflwyniad
  completion: engaged
- title: Animeiddio llong ofod
- title: 'Her: perffeithio dy animeiddiad'
  challenge: true
- title: Animeiddio yn defnyddio dolennu
- title: Mwnci yn arnofio
- title: Asteroid Sbonciog
  completion: internal
- title: Seren ddisglair
- title: 'Her: gwneud animeiddiad dy hunan'
  challenge: true
- title: Beth nesaf?
