---
title: Verschollen im Weltraum
hero_image: images/lost-in-space.png
description: Lerne eigene Animationen zu programmieren!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Einleitung
  - 
    title: Ein Raumschiff animieren
  - 
    title: 'Ein Raumschiff animieren'
    challenge: true
  - 
    title: Animieren mit Schleifen
  - 
    title: Schwebender Affe
  - 
    title: Abprallender Asteroid
  - 
    title: Glänzender Stern
  - 
    title: 'Challenge: Mache deine eigene Animation'
    challenge: true
  - 
    title: What next?
