---
title: Verschollen im Weltraum
hero_image: images/lost-in-space.png
description: Lerne eigene Animationen zu programmieren!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Einleitung
  - 
    title: Ein Raumschiff animieren
  - 
    title: 'Herausforderung: Verbessere deine Animation'
    challenge: true
  - 
    title: Animieren mit Schleifen
    completion:
      - engaged
  - 
    title: Schwebender Affe
  - 
    title: Abprallender Asteroid
  - 
    title: Glänzender Stern
    completion:
      - internal
  - 
    title: 'Challenge: Mache deine eigene Animation'
    challenge: true
  - 
    title: Wie geht es weiter?
