---
title: Elveszve az űrben
hero_image: images/lost-in-space.png
description: Tanuld meg, hogyan programozhatsz saját animációt!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Bevezetés
  - 
    title: Űrhajó animálása
  - 
    title: 'Kihívás: fejleszd az animációdat'
    challenge: true
  - 
    title: Animáció ismétlések használatával
    completion:
      - engaged
  - 
    title: Lebegő majom
  - 
    title: Pattogó aszteroida
  - 
    title: Ragyogó csillag
    completion:
      - internal
  - 
    title: 'Kihívás: készíts saját animációt'
    challenge: true
  - 
    title: What next?
