---
title: Perdidos en el espacio
hero_image: images/lost-in-space.png
description: "¡Aprende a programar tu propia animación!"
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 26/09/2018
steps:
- title: Introducción
  completion: engaged
- title: Animando una nave espacial
- title: 'Desafío: Mejora tu animación'
  challenge: true
- title: Animación usando bucles
- title: Mono flotante
- title: Asteroide rebotando
  completion: internal
- title: Una estrella brillante
- title: 'Desafío: Crea tu propia animación'
  challenge: true
- title: "¿Qué sigue?"
