---
title: Kadunud kosmoses
hero_image: images / lost-in-space.png
description: Lugege, kuidas oma animatsiooni programmeerida!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: nullist
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Sissejuhatus
  - 
    title: Kosmoselaeva animeerimine
  - 
    title: 'V채ljakutse: parandage oma animatsiooni'
    challenge: true
  - 
    title: Animatsioon silmuste abil
  - 
    title: Ujuv ahv
  - 
    title: Asteroidi kopsakas
  - 
    title: S채rav t채ht
  - 
    title: 'V채ljakutse: tehke oma animatsioon'
    challenge: true
  - 
    title: What next?
