---
title: Zagubiona w kosmosie
hero_image: images/lost-in-space.png
description: Naucz się, jak zaprogramować swoją własną animację!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
- title: Wprowadzenie
  completion: engaged
- title: Animowanie statku kosmicznego
- title: 'Wyzwanie: popraw swoją animację'
  challenge: true
- title: Animacja za pomocą pętli
- title: Pływająca małpa
- title: Odbijająca się asteroida
  completion: internal
- title: Świecąca gwiazda
- title: 'Wyzwanie: zrób własną animację'
  challenge: true
- title: Co dalej?
