---
title: Lost in space
hero_image: images/lost-in-space.png
description: Learn how to program your own animation!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Introduction
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Floating monkey
  - 
    title: Bouncing asteroid
  - 
    title: Shining star
  - 
    title: 'Challenge: make your own animation'
    challenge: true
  - 
    title: What next?
