---
title: স্থান হারিয়ে
hero_image: images/lost-in-space.png
description: কিভাবে নিজের এনিমেশন প্রোগ্রাম করা যায় তা শিখুন!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: স্ক্র্যাচ
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: ভূমিকা
  - 
    title: একটি স্পেসশিপ অ্যানিমেটিং করা
  - 
    title: 'চ্যালেঞ্জ: আপনার অ্যানিমেশন উন্নত করুন'
    challenge: true
  - 
    title: লুপগুলি ব্যবহার করে অ্যানিমেশন করুন
  - 
    title: ভাসমান বানর
  - 
    title: বাউন্সিং গ্রহাণু
  - 
    title: জ্বলন্ত তারা
  - 
    title: 'চ্যালেঞ্জ: আপনার অ্যানিমেশন তৈরি করুন'
    challenge: true
  - 
    title: এরপর কি?
