---
title: Izgubljeni u svemiru
hero_image: images/lost-in-space.png
description: Nauči kako da programiraš sopstvenu animaciju!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Uvod
  - 
    title: Animacija svemirskog broda
  - 
    title: 'Animacija svemirskog broda'
    challenge: true
  - 
    title: Animacija pomoću petlji
  - 
    title: Majmun koji pluta
  - 
    title: Asteroid koji poskakuje
  - 
    title: Zvijezda koja sija
  - 
    title: 'Izazov: napravi sopstvenu animaciju'
    challenge: true
  - 
    title: What next?
