---
title: Perdu dans l'espace
hero_image: images/lost-in-space.png
description: Apprends à programmer ta propre animation!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Introduction
  - 
    title: Animer un vaisseau spatial
  - 
    title: 'Défi : améliorer ton animation'
    challenge: true
  - 
    title: L'animation à l'aide de boucles
    completion:
      - engaged
  - 
    title: Singe flottant
  - 
    title: Astéroïde rebondissant
  - 
    title: Étoile brillante
    completion:
      - internal
  - 
    title: 'Défi: fait ta propre animation'
    challenge: true
  - 
    title: Et ensuite?
