---
title: Perduto nello Spazio
hero_image: images/lost-in-space.png
description: Impara a programmare la tua animazione!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - title: Introduzione
  - title: Animare un'astronave
  - title: 'Sfida: migliora la tua animazione'
    challenge: true
  - title: Animazioni usando i cicli
  - title: Scimmietta fluttuante
  - title: Asteroide che rimbalza
  - title: 'Stella splendente'
  - title: 'Sfida: crea la tua animazione'
    challenge: true
  - title: E adesso?
