---
title: Uzayda kaybolmuş
hero_image: images/lost-in-space.png
description: Kendi animasyonunuzu nasıl programlayacağınızı öğrenin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Giriş
  - 
    title: Bir uzay gemisini canlandırma
  - 
    title: 'Meydan Okuma: animasyonunuzu geliştirin'
    challenge: true
  - 
    title: Döngüler kullanarak animasyon yapma
    completion:
      - engaged
  - 
    title: Süzülen maymun
  - 
    title: Zıplayan asteroit
  - 
    title: Parlayan yıldız
    completion:
      - internal
  - 
    title: 'Meydan okuma: kendi animasyonunuzu yaratın'
    challenge: true
  - 
    title: Sırada ne var?
