---
title: Uzayda kaybolmuş
hero_image: images/lost-in-space.png
description: Kendi animasyonunuzu nasıl programlayacağınızı öğrenin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
- title: Giriş
  completion: engaged
- title: Bir uzay gemisini canlandırma
- title: 'Meydan Okuma: animasyonunuzu geliştirin'
  challenge: true
- title: Döngüler kullanarak animasyon yapma
- title: Süzülen maymun
- title: Zıplayan asteroit
  completion: internal
- title: Parlayan yıldız
- title: 'Meydan Okuma: kendi animasyonunuzu yaratın'
  challenge: true
- title: Sırada ne var?
