---
title: Uzayda kayboldum
hero_image: images / kayıp-in-space.png
description: Kendi animasyonunuzu nasıl programlayacağınızı öğrenin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: çizik
version: 4.1.3
last_tested: 2018/09/26
steps:
  - 
    title: Giriş
  - 
    title: Bir uzay gemisini canlandırmak
  - 
    title: 'Zorluk: animasyonunuzu geliştirin'
    challenge: true
  - 
    title: Döngüleri kullanarak animasyon
  - 
    title: Yüzen maymun
  - 
    title: Zıplayan asteroit
  - 
    title: Parlayan yıldız
  - 
    title: 'Zorluk: kendi animasyonunuzu yaratın'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
